name: Build and Deploy on Release

on:
  release:
    types:
      - created

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Use your project's Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Webpack build
      - name: Run Webpack build
        run: npm run build

      # Step 5: Prepare Release Branch
      - name: Prepare Release Branch
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract release tag (e.g., v1.0.0 -> v1)
          RELEASE_VERSION=${{ github.event.release.tag_name }}
          RELEASE_BRANCH=$(echo $RELEASE_VERSION | cut -d. -f1)
          git checkout -b $RELEASE_BRANCH

          # Set up Git identity
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Remove all files except the build output
          find . -type f ! -name '*.js' ! -path './dist/*' -exec rm -f {} +

          # Move build output to root directory
          mv dist/* .

          # Commit the changes
          git add .
          git commit -m "Release $RELEASE_VERSION"
          git push origin $RELEASE_BRANCH